server.servlet.context-path: '/API/v1/myshop'
server:
  port: ${PORT:9997}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${PROPS_REPO:C:\\Users\\AKropotov\\Downloads\\config}
          clone-on-start: true
          username: ${REPO_USER:git_geek}
          password: ${REPO_PASS:git_geek_pass}
  security:
    user:
      name: ${SERVER_USER:geek}
      password: ${SERVER_PASS:geek_pass}
